CC=gcc

OBJ_DIR ?= obj
DST_DIR ?= dst

CXXFLAGS = \
	-DENABLE_TRACE \
	-I ${OBJ_DIR}/zmqpp/include \
	-I ensure \
	-I mdp \
	-I modbus_tools \
	-Wall \
	-Wextra \
	-Wno-parentheses \
	-Wshadow \
	-Wunreachable-code \
	-g \
	-std=c++14

LDFLAGS = \
	-L ${OBJ_DIR}/zmqpp/lib \
	-lpthread \
	-lstdc++ \
	-lzmq \
	-lzmqpp

ifdef RELEASE

CXXFLAGS += \
	-O2 \
	-flto

else

CXXFLAGS += \
	-O0 \
	-fsanitize=address

LDFLAGS += \
	-fsanitize=address

endif
