CC=clang

FLAGS = \
	-DENABLE_TRACE \
	-Os \
	-Wall \
	-Wextra \
	-Wno-parentheses \
	-Wshadow \
	-Wunreachable-code \
	-fomit-frame-pointer \
	-g

ifndef RELEASE
	FLAGS +=  \
		-fsanitize=address
endif

CFLAGS = \
	$(FLAGS) \
	-std=gnu99

CXXFLAGS = \
	$(FLAGS) \
	-std=c++14 \

LDFLAGS = \
	-lstdc++ 

ifndef RELEASE
	LDFLAGS += \
		-fsanitize=address
endif
